name: gnulinuxmag
run-name: exemple.yml
on: push
jobs:
  etape1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5.0.0
      - run: bash merge-rebase.sh
      - run: echo "end of file"
